
/* Merged Plone Javascript file
 * This file is dynamically assembled from separate parts.
 * Some of these parts have 3rd party licenses or copyright information attached
 * Such information is valid for that section,
 * not for the entire composite file
 * originating files are separated by - filename.js -
 */

/* - promotion_gallery.js - */
// http://www.eea.europa.eu/portal_javascripts/promotion_gallery.js?original=1
(function($){$.fn.lofJSidernews=function(settings){return this.each(function(){new $.lofSidernews(this,settings)})};$.lofSidernews=function(obj,settings){this.settings={direction:'',mainItemSelector:'li',navInnerSelector:'ul',navSelector:'li',navigatorEvent:'click',wapperSelector:'.lof-main-wapper',interval:4000,auto:true,maxItemDisplay:3,startItem:0,navPosition:'vertical',navigatorHeight:100,navigatorWidth:310,duration:600,navItemsSelector:'.lof-navigator li',navOuterSelector:'.lof-navigator-outer',isPreloaded:true,easing:'easeInOutQuad',caption:'lof-main-item-desc',opacityClass:'.lof-opacity',toggleElement:'#pause-toggle'};$.extend(this.settings,settings||{});this.nextNo=null;this.previousNo=null;this.maxWidth=this.settings.mainWidth||600;$obj=$(obj);this.wrapper=$obj.find(this.settings.wapperSelector);this.slides=this.wrapper.find(this.settings.mainItemSelector);if(!this.wrapper.length||!this.slides.length){return}
if(this.settings.maxItemDisplay>this.slides.length){this.settings.maxItemDisplay=this.slides.length}
this.currentNo=isNaN(this.settings.startItem)||this.settings.startItem>this.slides.length?0:this.settings.startItem;this.navigatorOuter=$obj.find(this.settings.navOuterSelector);this.navigatorItems=$obj.find(this.settings.navItemsSelector);this.navigatorInner=this.navigatorOuter.find(this.settings.navInnerSelector);if(this.settings.navPosition==='horizontal'){this.navigatorInner.width(this.slides.length * this.settings.navigatorWidth);this.navigatorOuter.width(this.settings.maxItemDisplay * this.settings.navigatorWidth);this.navigatorOuter.height(this.settings.navigatorHeight)} else{this.navigatorInner.height(this.slides.length * this.settings.navigatorHeight);this.navigatorOuter.height(this.settings.maxItemDisplay * this.settings.navigatorHeight);this.navigatorOuter.width(this.settings.navigatorWidth)}
this.navigratorStep=this.__getPositionMode(this.settings.navPosition);this.directionMode=this.__getDirectionMode();if(this.settings.direction==='opacity'){this.wrapper.addClass(this.settings.opacityClass);$(this.slides).hide().eq(this.currentNo).show();this.caption=$obj.find(this.settings.caption);this.caption.hide().eq(0).show()} else{this.wrapper.css({'left':'-'+this.currentNo*this.maxSize+'px','width':(this.maxWidth) * this.slides.length})}
if(this.settings.isPreloaded){this.preLoadImage(this.onComplete)} else{this.onComplete()}};$.lofSidernews.fn=$.lofSidernews.prototype;$.lofSidernews.fn.extend=$.lofSidernews.extend=$.extend;$.lofSidernews.fn.extend({startUp:function(obj,wrapper){seft=this;this.navigatorItems.each( function(index,item){$(item).click( function(){seft.jumping(index,true);seft.setNavActive(index,item)});$(item).css({'height':seft.settings.navigatorHeight,'width':seft.settings.navigatorWidth})});this.setNavActive(this.currentNo);if(this.settings.buttons&&typeof(this.settings.buttons)==="object"){this.registerButtonsControl('click',this.settings.buttons,this)}
if(this.settings.auto){this.play(this.settings.interval,'next',true)}
if(this.settings.toggleElement){var gallery=this;$(this.settings.toggleElement).click( function(){if(this.innerHTML==="Pause"){gallery.stop();this.innerHTML="Play";this.className="play";return false}
else{gallery.play(1000,'next',true);this.innerHTML="Pause";this.className="pause";return false}})}
return this},onComplete:function(){setTimeout( function(){$('.preload').fadeOut(900)},400);this.startUp()},preLoadImage:function(callback){var self=this;var images=this.wrapper.find('img');var count=0;images.each( function(index,image){if(!image.complete){image.onload=function(){count++;if(count>=images.length){self.onComplete()}};image.onerror=function(){count++;if(count>=images.length){self.onComplete()}}}else{count++;if(count>=images.length){self.onComplete()}}})},navivationAnimate:function(currentIndex){if(currentIndex<=this.settings.startItem||currentIndex-this.settings.startItem>=this.settings.maxItemDisplay-1){this.settings.startItem=currentIndex-this.settings.maxItemDisplay+2;if(this.settings.startItem<0){this.settings.startItem=0}
if(this.settings.startItem>this.slides.length-this.settings.maxItemDisplay){this.settings.startItem=this.slides.length-this.settings.maxItemDisplay}}
this.navigatorInner.stop().animate(eval('({'+this.navigratorStep[0]+':-'+this.settings.startItem*this.navigratorStep[1]+'})'),{duration:500,easing:'easeInOutQuad'})},setNavActive:function(index,item){if((this.navigatorItems)){this.navigatorItems.removeClass('active');$(this.navigatorItems.get(index)).addClass('active');this.navivationAnimate(this.currentNo)}},__getPositionMode:function(position){if(position==='horizontal'){return ['left',this.settings.navigatorWidth]}
return ['top',this.settings.navigatorHeight]},__getDirectionMode:function(){if(this.settings.direction==='opacity'){this.maxSize=0;return ['opacity','opacity']}
else{this.maxSize=this.maxWidth;return ['left','width']}},registerButtonsControl:function(eventHandler,objects,self){for(var action in objects){if(objects.hasOwnProperty(action)){switch(action.toString()){case 'next':objects[action].click( function(){self.next(true);return false});break;case 'previous':objects[action].click( function(){self.previous(true);return false});break}}}
return this},onProcessing:function(manual,start,end){this.previousNo=this.currentNo+(this.currentNo>0?-1:this.slides.length-1);this.nextNo=this.currentNo+(this.currentNo<this.slides.length-1?1:1-this.slides.length);return this},finishFx:function(manual){if(manual){this.stop()}
if(manual&&this.settings.auto){this.play(this.settings.interval,'next',true)}
this.setNavActive(this.currentNo)},getObjectDirection:function(start,end){return eval("({'"+this.directionMode[0]+"':-"+(this.currentNo*start)+"})")},fxStart:function(index,obj,currentObj){if(this.settings.direction=='opacity'){var slides=$(this.slides);slides.fadeOut(1500);slides.eq(index).fadeIn(1500);$(currentObj.caption).fadeIn(1000)}
return this},jumping:function(no,manual){this.stop();if(this.currentNo==no){return}
var obj=eval("({'"+this.directionMode[0]+"':-"+(this.maxSize*no)+"})");this.onProcessing(null,manual,0,this.maxSize).fxStart(no,obj,this).finishFx(manual);this.currentNo=no},next:function(manual,item){this.currentNo+=(this.currentNo<this.slides.length-1)?1:(1-this.slides.length);this.onProcessing(item,manual,0,this.maxSize).fxStart(this.currentNo,this.getObjectDirection(this.maxSize),this).finishFx(manual);this.stopPlay()},previous:function(manual,item){this.currentNo+=this.currentNo>0?-1:this.slides.length-1;this.onProcessing(item,manual).fxStart(this.currentNo,this.getObjectDirection(this.maxSize),this).finishFx(manual);this.stopPlay()},play:function(delay,direction,wait){this.stop();if(!wait){this[direction](false)}
var self=this;this.isRun=setTimeout(function(){self[direction](true)},delay)},stopPlay: function(){var play_button=$(this.settings.toggleElement)[0];if(play_button.innerHTML==="Play"){this.stop()}},stop:function(){if(this.isRun===null){return}
clearTimeout(this.isRun);this.isRun=null}})})(jQuery);

/* - promo_gallery.js - */
// http://www.eea.europa.eu/portal_javascripts/promo_gallery.js?original=1
(function($){$(function(){var buttons={previous:$('#prev-promo'),next:$('#next-promo')};$("#promo-gallery-content img").each(
function(){this.width="448";this.height="320"});var small_navigator=$("#promo-navigator-sm"),site_address=small_navigator.length?true:undefined,nav_height=site_address?50:80,nav_width=site_address?65:170,nav_items_selector=site_address?"#promo-navigator-sm li":"#promo-navigator li",wrapper_selector=site_address?"#promo-gallery-content-sm":"#promo-gallery-content",max_item_display=site_address?5:3,nav_position=site_address?'horizontal':'vertical',nav_outer_selector=site_address?"#navigator-outer-sm":"#navigator-outer";var promotions=$('#promo-gallery-wrapper').lofJSidernews({interval:9000,direction:'opacity',duration:1500,wapperSelector:wrapper_selector,navItemsSelector:nav_items_selector,navOuterSelector:nav_outer_selector,isPreloaded:false,maxItemDisplay:max_item_display,navigatorHeight:nav_height,navigatorWidth:nav_width,navPosition:nav_position,auto:true,caption:'.promo-item-desc',opacityClass:'lof-opacity',buttons:buttons,toggleElement:'#play-pause'})})})(jQuery);

/* - whatsnew_gallery.js - */
// http://www.eea.europa.eu/portal_javascripts/whatsnew_gallery.js?original=1
jQuery(document).ready(function($){$("#highlights-high, #highlights-middle").tabs("div.highlightMiddle",{tabs:'div.panel',effect:'slide'});window.whatsnew={};var eea_gal=window.whatsnew;(function(){var host=window.location.href,host_length=host.length;eea_gal.site_address=host[host_length-1]!=='/'?host+'/':host;eea_gal.gallery=$("#whatsnew-gallery");eea_gal.gallery_page=eea_gal.gallery.attr("data-page")}());eea_gal.whatsnew_func=function(cur_tab_val,sel_text,sel_value,index,tag_title){var address=eea_gal.site_address+cur_tab_val+"_gallery_macro";var gal=eea_gal.gallery.find(".highlights");var news=index?gal[index]:gal.filter(function(){return this.style.display!=='none'});news=index===0?gal.first():news;news=news[0]!==undefined?news[0]:news;var filter_topic;filter_topic=news.firstElementChild!==undefined?news.firstElementChild:news.firstChild;var filter_topic_text="Filtered by <span>"+sel_text+"</span> topic";filter_topic.innerHTML=sel_value?filter_topic_text:"";var gallery_ajax=$(".gallery-ajax",news);var layout_selection=$('.gallery-layout-selection li a',news)[0];var params=sel_value?'topic'+'='+sel_value:undefined;params=tag_title?'tags'+'='+sel_value:params;gallery_ajax.load(address,params, function(html){var album=gallery_ajax.find('.gallery-album');var listing=gallery_ajax.find('.gallery-listing');if(html.length>1){if(layout_selection.className==="list-layout active-list"){gallery_ajax.find('.gallery-album').addClass('hiddenStructure');listing.hide().fadeIn('slow')}
else{gallery_ajax.find('.gallery-listing').addClass('hiddenStructure');album.hide().fadeIn('slow')}}})};$("ul#tabs, ul#multimedia-tabs").tabs("> .highlights", function(event,index){var cur_tab=this.getTabs()[index],cur_tab_val=cur_tab.id.substr(4);cur_tab.theme=cur_tab.theme||"none";var opt_item,sel_value,sel_text,tag_title;var highlight=$("#"+cur_tab_val+"-highlights");var gallery_ajax=highlight.find('.gallery-ajax');var ajax_loader_img='<div style="text-align: center;"><img src="++resource++faceted_images/ajax-loader.gif" /></div>';var tag_cloud=$("#bottomright-widgets").find('#tag-cloud-content');if(tag_cloud.length){var first_tag=tag_cloud.clone().detach();var address,topic_params,tags_params;var tabs=function(address,topic_params,tags_params){address=address||eea_gal.site_address+'all/@@tagscloud_counter';topic_params=topic_params||"cid=c1&c2=Products.EEAContentTypes.content.interfaces.IFlashAnimation&c3=all&c8=Animation+(swf)&c4=published&b_start=0";tags_params=tags_params||"cid=c3&c2=Products.EEAContentTypes.content.interfaces.IFlashAnimation&c3=all&c8=Animation+(swf)&c4=published&b_start=0";tag_cloud.load(address,topic_params, function(html){tag_cloud.find("#c1_widget").fadeIn();var themes=$("#c1");themes.tagcloud({type:'list',height:280,sizemin:12});var themes_li=themes.find('li');var theme_vals;theme_vals=themes_li.filter( function(){return this.value===1});theme_vals.remove();$.get(address,tags_params, function(data){tag_cloud.append(data);$("#c3_widget").fadeIn();var tags=$("#c3");tags.tagcloud({type:'list',height:280,sizemin:12});var vals=tags.find('li').filter( function(){return this.value===1});vals.remove();$("#faceted-tabs").tabs("#tag-cloud-content > div.faceted-widget");$('#c1all').addClass('selected');$('#c3all').addClass('selected')})})};switch(cur_tab_val){case "greentips":address=eea_gal.site_address+'all/@@tagscloud_counter';topic_params="cid=c1&c2=Products.EEAContentTypes.content.interfaces.IFlashAnimation&c3=all&c8=Animation+(swf)&c4=published&b_start=0";tags_params="cid=c3&c2=Products.EEAContentTypes.content.interfaces.IFlashAnimation&c3=all&c8=Animation+(swf)&c4=published&b_start=0";gallery_ajax.html(ajax_loader_img);tabs(address,topic_params,tags_params);break;case "videoclips":address=eea_gal.site_address+'all/@@tagscloud_counter';topic_params="cid=c1&c2=p4a.video.interfaces.IVideoEnhanced&c3=all&c8=&c4=published&b_start=0";tags_params="cid=c3&c2=p4a.video.interfaces.IVideoEnhanced&c3=all&c8=&c4=published&b_start=0";gallery_ajax.html(ajax_loader_img);tabs(address,topic_params,tags_params);break}}
opt_item=$("#topic-selector").find(":selected");if(opt_item.length){sel_value=opt_item.val();sel_text=opt_item.text()}
else{opt_item=$("#topright-widgets").find('.selected').filter(':visible');if(opt_item.length!==0){var tags=opt_item.parent().prev().text().indexOf('tags');sel_value=tags!==-1?opt_item[0].title:opt_item[0].id.substr(3);tag_title=tags!==-1?opt_item[0].title:undefined}
sel_text=opt_item.text();sel_value=sel_value!=='all'?sel_value:''}
var listing=highlight.find('.gallery-listing');var listing_length=listing.length!==0?listing.children().length:0;var notopics=highlight.find('.portalMessage'),notopics_length=notopics.length!==0?1:0;if(cur_tab.theme===sel_value&&notopics_length!==0){return}
if(sel_text.indexOf("All")!==-1||listing_length===0){listing.html(ajax_loader_img);eea_gal.whatsnew_func(cur_tab_val,sel_text,sel_value,index,tag_title)}
if(sel_value){if(cur_tab.theme!==sel_value){listing.html(ajax_loader_img);cur_tab.theme=sel_value;eea_gal.whatsnew_func(cur_tab_val,sel_text,sel_value,index,tag_title)}}});$topic_selector=$("#topic-selector");$topic_selector.find('[value="default"]').remove();$topic_selector.change(
function displayResult(){$topic_selector[0][0].className="hiddenStructure";var x=this.selectedIndex,y=this.options;var topic_value=y[x].value,topic_text=y[x].innerHTML;var tab_val=$("#tabs a.current, #multimedia-tabs a.current")[0].id.substr(4);eea_gal.whatsnew_func(cur_tab_val=tab_val,sel_text=topic_text,sel_value=topic_value)});var layout_links=$(".gallery-layout-selection li a");layout_links.click( function(e){var $this=$(this);var $parent=$this.parent();var $ajax=$this.closest('ul').next();var $hidden_gallery=$ajax.find(".hiddenStructure");var listing=$ajax.find('.gallery-listing');var album=$ajax.find('.gallery-album');var next=$parent.siblings().find('a');var link_class=$this[0].className;var highlight=$this.closest('div')[0].id;if(link_class==="list-layout active-list"||link_class==="album-layout active-album"){return false}
var cookie_expires=new Date();cookie_expires.setMonth(cookie_expires.getMonth()+1);if(link_class=="list-layout"){album.slideUp('slow');listing.slideDown('slow');$hidden_gallery.removeClass("hiddenStructure");$this.toggleClass("active-list");next.toggleClass("active-album");SubCookieUtil.set(eea_gal.gallery_page,highlight,"active-list",expires=cookie_expires);return false}
else{listing.slideUp('slow');album.slideDown('slow');$hidden_gallery.removeClass("hiddenStructure");$this.toggleClass("active-album");next.toggleClass("active-list");SubCookieUtil.set(eea_gal.gallery_page,highlight,"active-album",expires=cookie_expires);return false}});if(eea_gal.gallery.length>0){var gallery_cookies=SubCookieUtil.getAll(eea_gal.gallery_page);if(gallery_cookies!==null){eea_gal.gallery.find('.highlights').each(function(){var $this=$(this);var layouts=$this.find(".gallery-layout-selection li a");var $hidden_gallery=$this.find(".hiddenStructure");var link_listing=layouts.first();var link_album=layouts.last();var listing=$this.find('.gallery-listing');var album=$this.find('.gallery-album');var gallery_cookie=gallery_cookies[this.id];if(gallery_cookie!==null){if(gallery_cookie==="active-album"){listing.hide();album.show();$hidden_gallery.removeClass("hiddenStructure");link_listing.removeClass("active-list");link_album.addClass("active-album")}
else if(gallery_cookie==="active-list"){listing.show();album.hide();$hidden_gallery.removeClass("hiddenStructure");link_listing.addClass("active-list");link_album.removeClass("active-album")}}})}}});

/* - print_warning.js - */
// http://www.eea.europa.eu/portal_javascripts/print_warning.js?original=1
var warning_displayed=false;window.onbeforeprint=function(){var warning_text=jQuery.trim(jQuery("#print-warning p").html());if(warning_displayed===false){alert(warning_text)}};jQuery(document).ready(function($){$('#icon-print').parent().attr('href','#').click(function(){var warning_text=$.trim($("#print-warning p").html());if(confirm(warning_text)){warning_displayed=true;window.print()}})});

/* - framebreak.js - */
// http://www.eea.europa.eu/portal_javascripts/framebreak.js?original=1
function breakout_of_frame(){if(top.location!=location){top.location.href=document.location.href }}
jQuery(document).ready(function($){breakout_of_frame()});

/* - eea-fancybox.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-fancybox.js?original=1
jQuery(document).ready(function($){if($.fn.fancybox!==undefined){$('.fancybox').fancybox();$('.gallery-fancybox').each(function(){var href=$(this).attr('href')+"/gallery_fancybox_view";$(this).attr('href',href);$(this).fancybox({type:'iframe',padding:0,margin:0,width:780,height:580,scrolling:'no',autoScale:false,autoDimensions:false})})}});

/* - eea-mediacentre.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-mediacentre.js?original=1
(function($){$(document).ready(function(){
function prepareVideoLinkURLs(){$("#content, #vids-slider, #portal-column-two").delegate(".video-fancybox","hover", function(){var coverflow=$("#multimedia-coverflow"),video_page=coverflow.length>0?1:0;var parent=this;var href=this.href;var isInsidePopUp=$('body').hasClass('video_popup_view');if(video_page===0){if(href.indexOf('video_popup_view')===-1){this.href=href.replace(/view/,'video_popup_view')}}
var options={type:'iframe',padding:0,margin:0,width:675,height:564,scrolling:'no',autoScale:false,autoDimensions:false,centerOnScroll:false};if(video_page){if(href.indexOf('multimedia_popup_view')===-1){var regex=/view|video_popup_view|multimedia_popup_view/;var clean_href=href.replace(regex,'');this.href=clean_href+"multimedia_popup_view"}
var mult=coverflow.offset(),bg=window.whatsnew.multimedia.bg,bg2=window.whatsnew.multimedia.bg2,$parent=$(parent),src=$parent.find('img');var thumb_url=src.length!==0?src[0].src:$parent.closest('div').prev().children()[0].src;options.width=650;options.height=387;options.overlayShow=false;options.onStart=function(){var media_player=$("#media-player");if(media_player.is(":visible")){media_player.fadeOut('fast',function(){$("#contentFlow").fadeIn('slow')});$("#media-flowplayer").children().remove()}
$.fancybox.center=function(){return false};$('html, body').animate({scrollTop:0},200);$("#fancybox-wrap").css({position:'absolute'}).animate({left:mult.left-20,top:mult.top-20},200)};var info_area=function(iframe){var frame=iframe.contents();var tab_desc=frame.find("#tab-desc");var featured_item=$("#featured-items");var video_title=frame.find("#video-title").text();var featured_item_title=featured_item.find("h3");featured_item_title.text(video_title);var featured_description=featured_item.find(".featured-description");$("#featured-films").fadeOut();featured_description.html(tab_desc).end().fadeIn();var title_height=featured_item_title.height();var desc_height;if(title_height===21){desc_height="184px"}
else if(title_height===42){desc_height="163px"}
else{desc_height="142px"}
featured_description.css({height:desc_height});var orig_href=href.replace(/multimedia_popup_view/,'view');featured_item.find(".bookmark-link").attr("href",orig_href)};options.onComplete=function(){var iframe=$("#fancybox-frame");iframe.one("load",function(){info_area(iframe)})}}
if(!isInsidePopUp){$(this).fancybox(options)}})}
prepareVideoLinkURLs();if($.fn.fancybox===undefined){return}
if(window.Faceted){jQuery(Faceted.Events).bind(Faceted.Events.AJAX_QUERY_SUCCESS, function(evt){prepareVideoLinkURLs()})}})})(jQuery);
