
/* Merged Plone Javascript file
 * This file is dynamically assembled from separate parts.
 * Some of these parts have 3rd party licenses or copyright information attached
 * Such information is valid for that section,
 * not for the entire composite file
 * originating files are separated by - filename.js -
 */

/* - eea-autoscroll.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-autoscroll.js?original=1
jQuery(document).ready(function($){if($('.autoscroll-to-here').length){var top=$('.autoscroll-to-here').offset().top;$('html,body').animate({scrollTop:top},1000)}});

/* - eea-galleryview.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-galleryview.js?original=1
(function($){$(document).ready(function(){if($.fn.galleryView!==undefined){var $gallery_view=$('#galleryView');if($gallery_view.length){var $gallery_parent=$gallery_view.parent();var $gallery_class=$gallery_parent[0].className;var gallery_width=$gallery_class==='gallery_fancybox_view'?640:635;var gallery_height=$gallery_class==='gallery_fancybox_view'?433:423;$('#galleryView').galleryView({panel_width:gallery_width,panel_height:gallery_height,frame_width:50,frame_height:50,transition_speed:350,transition_interval:0})}}})}(jQuery));

/* - eea-tooltips.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-tooltips.js?original=1
jQuery(document).ready(function($){if($.fn.tooltip!==undefined){$(".eea-tooltip-top").each(function(i){var title=$(this).attr("title");$(this).tooltip({effect:'fade',tipClass:'eea-tooltip-markup-top'})});$(".eea-tooltip-bottom").each(function(i){var title=$(this).attr("title");$(this).tooltip({effect:'fade',position:'bottom center',tipClass:'eea-tooltip-markup-bottom'})});$(".eea-tooltip-left").each(function(i){var title=$(this).attr("title");$(this).tooltip({effect:'fade',position:'center left',tipClass:'eea-tooltip-markup-left'})});$(".eea-tooltip-right").each(function(i){var title=$(this).attr("title");$(this).tooltip({effect:'fade',position:'center right',tipClass:'eea-tooltip-markup-right'})});var removeExtraText=function(){this.getTip()[0].lastChild.nodeValue=''};$(".eea-flexible-tooltip-right").each(function(i){var title=$(this).attr("title");var container=$('<div>').addClass('eea-tooltip-markup');var bottomright=$('<div>').addClass('tooltip-box-br');var topleft=$('<div>').addClass('tooltip-box-tl');var content=$('<div>').addClass('tooltip-box-rcontent');content.text(title);topleft.append(content);bottomright.append(topleft);container.append(bottomright);$(this).tooltip({effect:'fade',position:'center right',offset:[20,20],tipClass:'eea-tooltip-markup',layout:container,onBeforeShow:removeExtraText})});$(".eea-flexible-tooltip-left").each(function(i){var title=$(this).attr("title");var container=$('<div>').addClass('eea-tooltip-markup');var bottomright=$('<div>').addClass('tooltip-box-br');var topleft=$('<div>').addClass('tooltip-box-tl');var content=$('<div>').addClass('tooltip-box-lcontent');content.text(title);topleft.append(content);bottomright.append(topleft);container.append(bottomright);$(this).tooltip({effect:'fade',position:'center left',offset:[20,-10],tipClass:'eea-tooltip-markup',layout:container,onBeforeShow:removeExtraText})});$(".eea-flexible-tooltip-top").each(function(i){var title=$(this).attr("title");var container=$('<div>').addClass('eea-tooltip-markup');var bottomright=$('<div>').addClass('tooltip-box-br');var topleft=$('<div>').addClass('tooltip-box-tl');var content=$('<div>').addClass('tooltip-box-tcontent');content.text(title);topleft.append(content);bottomright.append(topleft);container.append(bottomright);$(this).tooltip({effect:'fade',position:'top center',offset:[10,0],tipClass:'eea-tooltip-markup',layout:container,onBeforeShow:removeExtraText})});$(".eea-flexible-tooltip-bottom").each(function(i){var title=$(this).attr("title");var container=$('<div>').addClass('eea-tooltip-markup');var bottomright=$('<div>').addClass('tooltip-box-br');var topleft=$('<div>').addClass('tooltip-box-tl');var content=$('<div>').addClass('tooltip-box-bcontent');content.text(title);topleft.append(content);bottomright.append(topleft);container.append(bottomright);$(this).tooltip({effect:'fade',position:'bottom center',offset:[30,0],tipClass:'eea-tooltip-markup',layout:container,onBeforeShow:removeExtraText})})}});

/* - eea-toc.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-toc.js?original=1
function build_toc(){(function($){$('#document-toc').each(function(){var tocID=$(this).attr('id');var currentList=$(this).find('.portletItem ol');var hLevel=null;var lists={'root':currentList};var queryString=$('#queryString').html();$('#region-content').find(queryString).each(function(i,el){var newLevel=parseInt(el.tagName.charAt(1),10);hLevel=hLevel||newLevel;if(newLevel>hLevel){hLevel=newLevel;var newList=$('<ol></ol>');lists[newLevel]=newList;currentList.append(newList);currentList=newList} else if(newLevel<hLevel){hLevel=newLevel;currentList=lists[newLevel]||lists.root}
var h=$(el);var hText=$.trim(h.find('a').text())||h.text();var li=$('<li><a>'+hText+'</a></li>');var hId=h.attr('id')||'toc-'+i;var urlWithoutHash=location.protocol+'//'+location.host+location.pathname;li.find('a').attr('href',urlWithoutHash+'#'+hId);currentList.append(li);h.attr('id',hId);if(!h.find('.back-to-toc-button').length){var backButton=$('.eea-template.back-to-toc-button').clone();if(backButton.length){backButton.removeClass('eea-template');backButton.attr('href',urlWithoutHash+"#"+tocID);backButton.attr('title',"Back to table of contents");backButton.appendTo(h);h.addClass('header-with-go-back-button')}}});$('.collapsable-portlet .portletHeader').click(function(){var portletClicked=$(this).parents('.portlet');portletClicked.toggleClass('collapsed')})})}(jQuery))}
jQuery(document).ready(function($){$('#document-toc').find('ol').first().empty();build_toc();$("#region-content").find('.clear-toc').removeClass('clear-toc')});

/* - eea-fullscreen.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-fullscreen.js?original=1
jQuery(document).ready(function($){});

/* - eea-smartview.js - */
// http://www.eea.europa.eu/portal_javascripts/eea-smartview.js?original=1
jQuery(document).ready(function($){if($('#smart-view-switch').length){var markSelectedButton=function(){var smartTemplate=$.bbq.getState('smartTemplate');$('#smart-view-switch .selected').removeClass('selected');$('#smart-view-switch li').each(function(i){var templateID=$.trim($(this).text());if(templateID==smartTemplate){$(this).addClass('selected')}})};var loadCookieSetttings=function(){if($.bbq.getState('smartTemplate')===undefined&&readCookie('smartTemplate')){$.bbq.pushState({'smartTemplate':readCookie('smartTemplate')})}};var loadContent=function(){$('#smart-view-content').html('<img src="++resource++faceted_images/ajax-loader.gif" />');var url=$.param.querystring($.bbq.getState('smartTemplate'),$.param.querystring());$.get(url, function(data){$('#smart-view-content').html(data);$('.listingBar a').each(function(i){var batchQueryString=$.param.querystring($(this).attr('href'));var newUrl=$.param.querystring(location.href,batchQueryString);$(this).attr('href',newUrl)})},'html')};$('#smart-view-switch li').live('click', function(e){var smartTemplate=$(this).find('.template-id').text();$.bbq.pushState({'smartTemplate':smartTemplate});var ie6or7=$.browser.msie&&(parseInt($.browser.version,10)<=7);if(window.Faceted){if(Faceted.Window.width&&ie6or7){Faceted.Query=Faceted.URLHandler.hash2query(location.hash);$(Faceted.Events).trigger(Faceted.Events.QUERY_CHANGED);Faceted.Form.do_form_query()}}
createCookie('smartTemplate',smartTemplate)});loadCookieSetttings();$(window).bind('hashchange', function(e){if(window.Faceted){if(!Faceted.Window.width&&($.bbq.getState('smartTemplate')!==undefined)){markSelectedButton();loadContent()}}}).trigger('hashchange')}});

/* - slide.js - */
// http://www.eea.europa.eu/portal_javascripts/slide.js?original=1
(function($){var langregex1=new RegExp("(http://[a-z0-9.:]*)/(aa|ab|af|am|ar|as|ay|az|ba|be|bg|bh|bi|bn|bo|bs|br|ca|ch|co|cs|cy|da|de|dz|el|en|eo|es|et|eu|fa|fi|fj|fo|fr|fy|ga|gd|gl|gn|gu|gv|ha|he|hi|hr|hu|hy|ia|id|ie|ik|is|it|iu|ja|jbo|jw|ka|kk|kl|km|kn|ko|ks|ku|kw|ky|la|lb|li|ln|lo|lt|lv|mg|mi|mk|ml|mn|mo|mr|ms|mt|my|na|ne|nl|no|nn|oc|om|or|pa|pl|ps|pt|qu|rm|rn|ro|ru|rw|sa|sd|se|sg|sh|si|sk|sl|sm|sn|so|sq|sr|ss|st|su|sv|sw|ta|te|tg|th|ti|tk|tl|tn|to|tr|ts|tt|tw|ug|uk|ur|uz|vi|vo|wa|wo|xh|yi|yo|za|zh|zu)/.*");var langregex2=new RegExp("(http://[a-z0-9.:]*/)(aa|ab|af|am|ar|as|ay|az|ba|be|bg|bh|bi|bn|bo|bs|br|ca|ch|co|cs|cy|da|de|dz|el|en|eo|es|et|eu|fa|fi|fj|fo|fr|fy|ga|gd|gl|gn|gu|gv|ha|he|hi|hr|hu|hy|ia|id|ie|ik|is|it|iu|ja|jbo|jw|ka|kk|kl|km|kn|ko|ks|ku|kw|ky|la|lb|li|ln|lo|lt|lv|mg|mi|mk|ml|mn|mo|mr|ms|mt|my|na|ne|nl|no|nn|oc|om|or|pa|pl|ps|pt|qu|rm|rn|ro|ru|rw|sa|sd|se|sg|sh|si|sk|sl|sm|sn|so|sq|sr|ss|st|su|sv|sw|ta|te|tg|th|ti|tk|tl|tn|to|tr|ts|tt|tw|ug|uk|ur|uz|vi|vo|wa|wo|xh|yi|yo|za|zh|zu)$");
function isCurrentPageTranslated(){var link=document.location.href.toLowerCase();return langregex1.test(link)||langregex2.test(link)}
$(document).ready(function(){if($.browser.msie&&parseInt($.browser.version,10)<7){return}
function panel(i){var a=$(this);var buttonID=a.parent().attr('id');var tooltip=$('#tip-'+buttonID);if(buttonID==="siteaction-contactus"&&isCurrentPageTranslated()){return}
var article_lang=buttonID==="article-language";var networks_panel=buttonID==="externalsites-networks";if(tooltip.length>0){a.attr("title","").attr("href","#");fordef='click, blur';a.tooltip({tip:tooltip[0],position:'bottom center',offset:[0,0],delay:10000000,events:{def:fordef}});a.click(function(ev){ev.preventDefault();var parents=$('#cross-site-top, #content'),panels=parents.find('.panel');panels.each(function(){if($(this).attr('id')!==tooltip.attr('id')){$(this).fadeOut('fast')}});if(article_lang){$("#tip-article-language").css({position:'absolute',top:'48px',display:'block',right:'0px',left:''})}
if(networks_panel){$("#tip-externalsites-networks").css('margin-left','2em')}
tooltip.fadeIn('fast')})}}
$(document).click(function(e){var target=$(e.target);var parents=$('#cross-site-top, #content'),panels=parents.find('.panel');if(!target.is('#cross-site-top a,  #cross-site-top .panel, #article-language a')&&!target.parents('.panel').length){panels.fadeOut('fast')}});$("#portal-siteactions a").each(panel);$("#portal-externalsites a").each(panel);$("#article-language").find('a').each(panel);$("#tip-externalsites-networks").find(".externalsites a").each(panel);var footer=$("#tip-siteaction-events .portletFooter");var submitLink=$("#tip-siteaction-events #submit-event-link");submitLink.remove().css('margin-right','0.5em');footer.prepend(submitLink)})}(jQuery));

/* - soer_frontpage.js - */
// http://www.eea.europa.eu/portal_javascripts/soer_frontpage.js?original=1
(function($){$(document).ready(function(){var slide_portlet=$('.slidePortlet');if(slide_portlet.length===0){return}
var body=$('body'),body_class=body.attr('class').match(/\bsoer/);slide_portlet.each(function(){var portlet=$(this);var b1=$('<span class="slideButton next"></span>');var b2=$('<span class="slideButton prev"></span>');portlet.append(b1);portlet.append(b2);var play=$('<div class="slideButton play"></div>');portlet.append(play);var items=portlet.find('.portletItem');var randomnumber=Math.floor(Math.random()*items.length);var elem=items[randomnumber];$(elem).addClass('selected');$(elem).css('left',0);b1.click(function(){var current=portlet.find('.portletItem.selected');var next=current.next('.portletItem');var currentIndex=portlet.find('.portletItem').index(current);var nextIndex=portlet.find('.portletItem').index(next);if(currentIndex+1==portlet.find('.portletItem').length){return}
current.removeClass('selected');next.addClass('selected');current.animate({'left':-(portlet.width()+100)});next.animate({'left':0})});b2.click(function(){var current=portlet.find('.portletItem.selected');var next=current.prev('.portletItem');var currentIndex=portlet.find('.portletItem').index(current);var nextIndex=portlet.find('.portletItem').index(next);if(currentIndex===0){return}
current.removeClass('selected');next.addClass('selected');var p=portlet.width()+100;current.animate({'left':portlet.width()+100});next.animate({'left':0})});var playID;play.click( function(){var $this=$(this);if($this.hasClass('pause')){$this.removeClass('pause');window.clearInterval(playID)}
else{$this.toggleClass('pause');b1.click();playID=window.setInterval(function(){b1.click()},10000)}});if(body_class){play.addClass('pause');playID=window.setInterval(function(){b1.click()},10000)}})})})(jQuery);

/* - global_searchbox.js - */
// http://www.eea.europa.eu/portal_javascripts/global_searchbox.js?original=1
(function($){$(function(){var search_forms=$("#portal-searchbox, #visual-column-wrapper").find(".searchforms");var text_inputs=search_forms.find("input:text");text_inputs.each( function(){var search_label=this.title+"...";this.onfocus=function(){if(this.value==search_label){this.value=""}};this.onblur=function(){if(this.value===""){this.value=search_label}};this.value=search_label})})})(jQuery);
